// Generated by https://quicktype.io

export interface ApplicationSetting {
  application:    Application;
  paymentSetings: PaymentSetings;
  email:          Email;
  social:         Social;
}

export interface Application {
  title:             string;
  theme:             string;
  emailConfirmation: boolean;
  logo:              string;
  favicon:           string;
  language:          string;
}

export interface Email {
  host:              string;
  port:              string;
  encryptioon:       string;
  useAuthentication: boolean;
  username:          string;
  password:          string;
  fromEmail:         string;
  fromName:          string;
}

export interface PaymentSetings {
  stripe: Stripe;
  paypal: Paypal;
}

export interface Paypal {
  clientId: string;
  secret:   string;
  mode:     string;
  enable:   boolean;
}

export interface Stripe {
  publishableKey: string;
  secretKey:      string;
  enable:         boolean;
}

export interface Social {
  youtube:   string;
  twitch:    string;
  github:    string;
  instagram: string;
  facebook:  string;
  twitter:   string;
}
